### ISSUE TITLE
One can modify elements of a REALMATRIX using const methods.

### ISSUE THREAD

**Issue by donghyunismyname** [fbrausse/iRRAM#4]
https://github.com/fbrausse/iRRAM/blob/master/include/iRRAM/REALMATRIX.h

From line 53 through 57 I noticed that the two methods are `const`.
```
REAL&   operator ()           (unsigned int row,
                               unsigned int column) const;

REAL&   element               (unsigned int row,
                               unsigned int column) const;
```
However, one can modify (in a high-level sense) elements of a REALMATRIX using these methods.

Consider a function.
```
void foo (const REALMATRIX &M) {
    M(0, 0) = 123;
}
```
Compile errors are not raised since `operator()` is `const`.

I suggest the following fix.
```
REAL&   operator ()           (unsigned int row,
                               unsigned int column);

REAL   element               (unsigned int row,
                               unsigned int column) const;
```

I think this is a better design, but I cannot really handle the dependencies and side effects introduced by this fix.

**Comment by fbrausse** [comment]
Many thanks @donghyunismyname! I very much agree and put this change in in f1c7a916.
